export const PAGE_LIFECYCLE_STATE_HIDDEN = 'hidden';
export const PAGE_LIFECYCLE_STATE_ACTIVE = 'active';
export const PAGE_LIFECYCLE_STATE_PASSIVE = 'passive';
export const PAGE_LIFECYCLE_STATE_FROZEN = 'frozen';
export const PAGE_LIFECYCLE_STATE_TERMINATED = 'terminated';

export const PAGE_LIFECYCLE_STATES = new Set([
  PAGE_LIFECYCLE_STATE_ACTIVE,
  PAGE_LIFECYCLE_STATE_FROZEN,
  PAGE_LIFECYCLE_STATE_HIDDEN,
  PAGE_LIFECYCLE_STATE_PASSIVE,
  PAGE_LIFECYCLE_STATE_TERMINATED,
]);

export const DOCUMENT_STATE_DOM_LOADED = 'domLoaded';
export const DOCUMENT_STATE_FULLY_LOADED = 'fullyLoaded';
export const DOCUMENT_STATE_COMPLETE = 'complete';
export const DOCUMENT_STATE_INTERACTIVE = 'interactive';
export const DOCUMENT_STATE_LOADING = 'loading';

export const DOCUMENT_STATES = new Set([
  DOCUMENT_STATE_COMPLETE,
  DOCUMENT_STATE_DOM_LOADED,
  DOCUMENT_STATE_FULLY_LOADED,
  DOCUMENT_STATE_INTERACTIVE,
  DOCUMENT_STATE_LOADING,
]);

export const PAGE_LIFECYCLE_STATE_CHANGE_EVENT = 'pageLifecycleStateChange';
export const DOCUMENT_STATE_CHANGE_EVENT = 'documentStateChange';
